twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        shared:
          appTitle: "MeeHou"
          appBaseURL: "https://meehou.app"
          appLogo: 'build/theme/ablepro/images/logo-dark.svg'
          developerTitle: "Reformsoft Teknoloji A.Ş."
          developerURL: "https://www.reformsoft.net/"

        admin:
            charset: "utf-8"
            favicon: 'build/theme/ablepro/images/favicon.svg'
            meta:
                - key: "description"
                  value: "Lorem ipsum dolor sit amet..."
            sidebar:
              - header: "SUMMARY"
              - name: "Dashboard"
                icon: "ti ti-home"
                path: 'app_admin_dashboard'
              - name: "sgdsdgsdg"
                icon: "ti ti-home"
                path: 'app_admin_documentation'
                items:
                  - name: "sdgsdg"
                    path: "app_admin_documentation"
              - header: "Development Proccess"
              - name: "Documentation"
                icon: "ti ti-flask"
                path: 'app_admin_documentation'
        misc:
            coming_soon:
                year: 2023
                month: 7
                day: 1

when@test:
    twig:
        strict_variables: true
